# Generated by Django 4.2.6 on 2024-11-24 18:11

from django.db import migrations, models
import input_project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(default=input_project.models.generate_project_id, max_length=14, unique=True)),
                ('input_data', models.FilePathField()),
                ('used_parameters', models.JSONField()),
                ('project_completed', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('run_duration', models.DurationField(blank=True, null=True)),
                ('output_data', models.FilePathField(blank=True, null=True)),
            ],
        ),
    ]
