# Generated by Django 4.2.6 on 2024-11-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_dir',
            field=models.CharField(default='/Users/stavris/Desktop/Projects/nStringAnalysis/nanoinsights/src/nanosite/input_project/uploads', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='input_data',
            field=models.FileField(upload_to='input_data/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='output_data',
            field=models.FileField(blank=True, null=True, upload_to='output_data/'),
        ),
    ]
